# Generated by Django 4.1.6 on 2023-02-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtypes',
            name='url',
            field=models.SlugField(default='q', max_length=255, unique=True),
        ),
    ]
