# Generated by Django 4.1.6 on 2023-02-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0003_instructors_url_locality_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genders',
            options={'verbose_name': 'пол', 'verbose_name_plural': 'пол'},
        ),
        migrations.AlterModelOptions(
            name='instructors',
            options={'verbose_name': 'тренер', 'verbose_name_plural': 'тренеры'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'место проведения тренинга', 'verbose_name_plural': 'места проведения тренингов'},
        ),
        migrations.AlterModelOptions(
            name='trainings',
            options={'verbose_name': 'тренинг', 'verbose_name_plural': 'тренинги'},
        ),
        migrations.AlterModelOptions(
            name='trainingtypes',
            options={'verbose_name': 'тип тренинга', 'verbose_name_plural': 'типы тренинга'},
        ),
        migrations.AlterField(
            model_name='instructors',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sam.genders', verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='trainings',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sam.locality', verbose_name='место проведения тренинга'),
        ),
        migrations.AlterField(
            model_name='trainings',
            name='trainingType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sam.trainingtypes', verbose_name='тип тренинга'),
        ),
    ]
