# Generated by Django 4.1.6 on 2023-02-18 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0004_alter_genders_options_alter_instructors_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='image',
            field=models.ImageField(null=True, upload_to='instructors', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='Shedulers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtChange', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('dtStart', models.DateTimeField(default=datetime.date.today, verbose_name='дата начала')),
                ('dtEnd', models.DateTimeField(default=datetime.date.today, verbose_name='дата завершения')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('instructors', models.ManyToManyField(related_name='traning_part_instructor', to='sam.instructors', verbose_name='тренеры')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sam.trainings', verbose_name='тренинг')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'расписания',
            },
        ),
    ]
