# Generated by Django 4.1.6 on 2023-02-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0006_shedulers_name_alter_shedulers_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedulers',
            name='dtEnd',
            field=models.DateTimeField(verbose_name='дата завершения'),
        ),
        migrations.AlterField(
            model_name='shedulers',
            name='dtStart',
            field=models.DateTimeField(verbose_name='дата начала'),
        ),
    ]
