# Generated by Django 4.1.6 on 2023-02-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0008_alter_shedulers_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
