# Generated by Django 4.1.6 on 2023-02-23 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0009_trainings_description_alter_instructors_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sam.reviews', verbose_name='Родитель')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sam.trainings', verbose_name='Тренинг')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
