# Generated by Django 4.1.6 on 2023-03-13 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0012_articles_reviews_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='dtInsert',
            field=models.DateTimeField(default=datetime.date.today, null=True, verbose_name='дата изменения'),
        ),
    ]
