# Generated by Django 4.1.6 on 2023-03-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0013_reviews_dtinsert'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='instructors',
            name='mobphone',
            field=models.CharField(max_length=254, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='instructors',
            name='tg',
            field=models.URLField(max_length=254, null=True, verbose_name='страница Telegramm'),
        ),
        migrations.AddField(
            model_name='instructors',
            name='vk',
            field=models.URLField(max_length=254, null=True, verbose_name='страница ВК'),
        ),
    ]
