# Generated by Django 4.1.6 on 2023-03-21 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0015_alter_trainings_dtend_alter_trainings_dtstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings',
            name='dtEnd',
            field=models.DateField(default=datetime.date.today, verbose_name='дата завершения'),
        ),
        migrations.AlterField(
            model_name='trainings',
            name='dtStart',
            field=models.DateField(default=datetime.date.today, verbose_name='дата начала'),
        ),
    ]
